version: '2.2'

services:
  web:
    image: git.ecwid-labs.com:4567/APP_PROJECT/NAME:VERSION
    ports:
      - "8081:80"
    restart: "on-failure:10"
    cpu_shares: 512
    mem_limit: 64m
    build:
      context: .

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.42.28.0/24
